#!/bin/bash

pkgName=${BASH_SOURCE##*/}  #get package name from file name
pkgDescription="template pkgfile"

# separate packages w/ spaces
# can be left blank
dependsLocal="" 	#pkgdl packages
dependsSystem=""	#pkgs from your system package manager
systemPkg=""		#e.g. 'dnf install -y', 'pacman -S', etc

# commands to check current and latest version of pkg, as this example
# must be _only_ the version, e.g. 18.0.4
currentVersion="$(hyprctl version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')"
latestVersion="$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/hyprwm/Hyprland/releases/latest | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')"


# logging is done automatically by pkgdl, as is entering/removing work directory :)
build() {

	# everything needed to install the package goes here (pulling binary, copying files, or building source, etc.)	

}


##
##  below should not need to be changed, make sure you know what you're doing !
##
update() {
	if versionCheck "$currentVersion" "$latestVersion"; then upToDate=1; else [[ "$checkUpdateOnly" = "yes" ]] && notify-send "pkgdl" "update available for: $pkgName"; fi
	return 0
}
main() {
	case "${1,,}" in
		*"layabout"*) true ;;
		*"check"*) update ;;
		*"build"*) build ;;
		*) update && if [[ ! "$upToDate" -eq 1 ]]; then build; fi ;;
	esac
}
set -e
main "$@"
