#!/bin/bash

##
## pkgs/template: pkgdl file for template
##

# fail on error
set -e

# modify version variables to apply for your package, must be only the version e.g. 3.2.1
declare -r template_CurrentVersion="$(hyprctl version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')"
declare -r template_LatestVersion="$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/hyprwm/Hyprland/releases/latest | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')"
declare -r pkgName=${BASH_SOURCE##*/}

needsUpdate() {
	# compare local pkg version to latest
	# this shouldn't need to be changed
	
	if versionCheck "$template_CurrentVersion" "$template_LatestVersion"; then
		echo "$pkgName is up to date"
		exit 0
	else
		# only notify if we're not upgrading, otherwise upgrade
		[[ "$checkUpdateOnly" = "yes" ]] && notify-send "pkgdl" "update available for: $pkgName"
		return 0
	fi
}

get() {
	# enter work directory
	mkdir -p "$pkgdl_WorkDirectory"/"$pkgName" && cd "$_"


	## ...  do everything needed to install the package here (pulling binary, copying files, etc.)  ... ##


	# things are done, remove our work directory
	rm -rf "$pkgdl_WorkDir"/"$pkgName"
}

main() {
	# this shouldn't need to be changed either

	shift
	case "$1" in
		"get"|"")
			needsUpdate
			get
			;;
		"latest")
			declare checkUpdateOnly="yes"
			needsUpdate
			;;
		*)
			fatal "unknown option $1"
	esac
}


main "$@"
