#!/bin/bash

##
## pkgs/hyprland: pkgdl file for hyprland
##

# fail on error
set -e

# modify version variables to apply for your package, must be only the version e.g. 3.2.1
declare -r hyprland_CurrentVersion="$(hyprctl version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')"
declare -r hyprland_LatestVersion="$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/hyprwm/Hyprland/releases/latest | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')"
declare -r pkgName=${BASH_SOURCE##*/}


needsUpdate() {
	# compare local pkg version to latest
	# this shouldn't need to be changed
	
	if versionCheck "$hyprland_CurrentVersion" "$hyprland_LatestVersion"; then
		echo "$pkgName is up to date"
		exit 0
	else
		# only notify if we're not upgrading, otherwise upgrade
		[[ "$checkUpdateOnly" = "yes" ]] && notify-send "pkgdl" "update available for: $pkgName" || get
		return 0
	fi
}

get() {
	# enter work directory
	mkdir -p "$pkgdl_WorkDirectory"/"$pkgName" && cd "$_"

	# pull newest version
	curl -fLO https://github.com/hyprwm/Hyprland/releases/download/v"$hyprland_LatestVersion"/v"$hyprland_LatestVersion".tar.gz
	tar xf "v$hyprland_LatestVersion".tar.gz && rm "$_"
	cd hyprland

	# copy binaries and voila; hyprland is upgraded
	sudo cp -v libwlroots.so.12032 /usr/lib64  #OpenMandriva, openSUSE, & prob others, /usr/lib isn't the right place
	sudo cp -v {hyprctl,Hyprland} /usr/bin

	# things are done, remove our work directory
	rm -rf "$pkgdl_WorkDirectory"/"$pkgName"
}

main() {
	shift
	case "$1" in
		"get"|"")
			needsUpdate
			get
			;;
		"latest")
			declare checkUpdateOnly="yes"
			needsUpdate
			;;
		*)
			fatal "unknown option $1"
	esac
}


main "$@"
