#!/bin/bash

pkgName=${BASH_SOURCE##*/} 
pkgDescription="The easiest, most secure way to use WireGuard and 2FA"

dependsLocal=""
dependsSystem=""
systemPkg="dnf install -y"
currentVersion="$(tailscale version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')"
latestVersion="$(curl -Ls -o /dev/null -w %{url_effective} https://pkgs.tailscale.com/stable/tailscale_latest_amd64.tgz | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')"

build() {
	curl -fLO https://pkgs.tailscale.com/stable/tailscale_"$latestVersion"_amd64.tgz
	tar xf tailscale_"$latestVersion"_amd64.tgz && rm tailscale_"$latestVersion"_amd64.tgz
	cd tailscale_"$latestVersion"_amd64
	sudo cp -v tailscaled /usr/sbin/
	sudo cp -v tailscale /usr/bin/
	sudo cp -v systemd/tailscaled.service /etc/systemd/system/
	sudo cp -v systemd/tailscaled.defaults /etc/default/tailscaled
}


##
##  below should not need to be changed, make sure you know what you're doing !
##
update() {
	if versionCheck "$currentVersion" "$latestVersion"; then upToDate=1; else [[ "$checkUpdateOnly" = "yes" ]] && notify-send "pkgdl" "update available for: $pkgName"; fi
	return 0
}
main() {
	case "${1,,}" in
		*"layabout"*) true ;;
		*"check"*) update ;;
		*"build"*) build ;;
		*) update && if [[ ! "$upToDate" -eq 1 ]]; then build; fi ;;
	esac
}
set -e
main "$@"
